### ISSUE TITLE
Simulator needs to use base1024

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/grid_weblets#1011]
### Description

Minting code uses base 1024 to calculate the farming rewards, while the simulator lets users fill in their GB which often uses a different base. This causes a lot of confusion and complaints from people saying they're getting fewer tokens than what the simulator shows them they should get. 

Need to make it very clear that they need to use base 1024 while filling in the simulator, otherwise there might be a different payout.

**Comment by mohamedamer453** [comment]
Verified locally since the simulator is only available on mainnet.

A note was added in both the `DIY` & `Titan` calculators clarifying that the user should use base `1024` for the calculations.

![image](https://user-images.githubusercontent.com/101194226/201953485-f8a7ad30-818d-49bc-b569-11bb7bb2ae65.png)

![image](https://user-images.githubusercontent.com/101194226/201953554-7de897a9-c6fe-4305-ab53-ae4938e9cf63.png)

Since this issue was verified locally i'll leave it open until it's released on mainnet and i can re-verify it there.
