### ISSUE TITLE
upgrade discourse weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1081]
the image used in the forum is quite oudated 
![image](https://user-images.githubusercontent.com/64129/200160449-e03570db-de1f-48f7-80fd-329a49aa8ba1.png)

Let's make sure to have an updated image that's used by both the forum and the playground.

**Comment by Omarabdul3ziz** [comment]
work on this issue was paused due to other urgent work. and back to in progress now

**Comment by Omarabdul3ziz** [comment]
update: done with adding the threefold auth to a recent fork of the official code. and wip on creating the docker image.

**Comment by Omarabdul3ziz** [comment]
update: work is paused here due to other argent issue

**Comment by Omarabdul3ziz** [comment]
work on the image is done. but waiting for:
- transfer the fork to threefoldtech https://github.com/Omarabdul3ziz/tf-forum3 and update links in dockerfile
- hub.grid.tf to be fixed to build the flist

changes in the weblets:
- increase the disksize to be at least 25 instead of 10 GB at `/var/lib/docker`

**Comment by Omarabdul3ziz** [comment]
Updates:
- the latest working flist is https://hub.grid.tf/omarabdulaziz.3bot/threefolddev-forum-docker-v3.1.flist with entry point `/sbin/zinit init`
- Recommended capacity: 2 cpu core, 4GB Ram, at least 25GB disk space mounted at `/var/lib/docker`
- the [dockerfile](https://github.com/threefoldtech/tf-images/blob/development_upgrade_forum/tfgrid3/forum-3/README.md)

Ongoing work?
- trying to optimize the upgrade process by not forking the main discourse repo and instead adding threebot login as a plugin so that will make each instance updated with the changes in the main discourse repo.

**Comment by Omarabdul3ziz** [comment]
Track the plugin work progress on a separate issue: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/118

**Comment by Omarabdul3ziz** [comment]
Update: 
the mentioned pr above changes the flist to `https://hub.grid.tf/tf-official-apps/forum-docker-v3.1.flist` which contains a fork version of discourse base code with a server implementation for threefold connect auth.

For updates on the plugin. Track threefoldtech/tfgrid-sdk-ts#118

**Comment by A-Harby** [comment]
Verified on Devnet, ade2f1e.
Discourse flist image is upgraded.
![image](https://user-images.githubusercontent.com/109473873/216013961-8775c645-3ade-4541-a166-25a3da2890e4.png)
