### ISSUE TITLE
nixos support in full vms

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1103]

**Comment by ashraffouda** [comment]
for full vm 
we tried to make a full vm using https://github.com/nix-community/nixos-generators but for some reason the resulting image not booted successfully
![Screenshot from 2022-11-18 16-41-48](https://user-images.githubusercontent.com/1689456/202730709-7dee6697-c2bb-44af-9d78-895faaec116a.png)
although thoses disks appears on the resulting image when we mounted it and it's label is correct

**Comment by ashraffouda** [comment]
the image build now succeeded, loaded with cloud-hypervisor successfully, cloud-init is working properly
but for some reason it didn't boot on the grid still investigating why

**Comment by ashraffouda** [comment]
Image is done, for /etc/nixos/configuration.nix we can not make the user to enter it during deployment because for full vms we only can pass data through cloud-init and we can not add files like configuration.nix 
also files like default.nix and shell.nix the user should add them after he do ssh to the machine according to this issue https://github.com/nix-community/nixos-generators/issues/193
