### ISSUE TITLE
deploy button is enabled while validating the node 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1182]
after select the node from dropdown list, it will be validated and the button is disabled, but in ping node phase the button is enabled

![image](https://user-images.githubusercontent.com/62248851/209473659-f86dd340-9ff1-48ec-81c5-f3383f6eb347.png)

**Comment by A-Harby** [comment]
Devnet, e51d47f.

Can't deploy with manual node selection.

Steps to reproduce:
- Select any deployment and fill all inputs.
- Choose capacity filter as node selection.
- Apply and wait for the deploy button to enabled.
- Choose manual instead of capacity filter. 
(Repeat last 2 steps and It will always be reproducible).  

[Untitled_ Dec 29, 2022 4_27 PM.webm](https://user-images.githubusercontent.com/109473873/209967388-15f5a435-4672-4705-845a-45ee5b7a5ff0.webm)

**Comment by 0oM4R** [comment]
should be solved in  #1212

**Comment by A-Harby** [comment]
Verified on Devent, cf2486d.
Now whenever I change node capacity choice, it restarts and only applies when user press the button.
![image](https://user-images.githubusercontent.com/109473873/212546895-29a95b2f-216a-43af-8bdb-f92e929e954f.png)
