### ISSUE TITLE
Owncloud stuck on filtering node with capacity filter

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1218]
### Description

After filling in all the input and choosing capacity filter as Node Selection, it keeps loading forever after pressing apply button.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/210554495-b7369aa2-45d3-48f0-acb5-183695a67a30.png)
![image](https://user-images.githubusercontent.com/109473873/210554930-a13ec1ad-1c74-438f-ae68-14fb14b091b6.png)

**Comment by Omarabdul3ziz** [comment]
couldn't catch the error but while debugging the following is noticed:
- it only happens when choosing the gateway node
- it can happen with the manual node selection also it will keep validating and the same error will be logged.
  ![image](https://user-images.githubusercontent.com/32527347/210583337-e8dfbdd7-468c-4314-82e6-238e8a7fa572.png)

**Comment by A-Harby** [comment]
Verified on Devnet, 6a23645.
Apply filter is now working fine and deploying successfully.. 
![image](https://user-images.githubusercontent.com/109473873/211517259-9ca3f1f4-1222-435f-9fc6-90ef0326e94d.png)
