### ISSUE TITLE
The back button returns an error

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1287]
#### after deploying subscuid, whether the deployment succeeded or failed, if you click on the Back button to return to the configuration section it will return this error on the first click,
![image](https://user-images.githubusercontent.com/62248851/216960917-7e7d799e-6403-48f6-afd1-c3376761f8e5.png)
#### if you click again it will try to deploy subscuid as the logs say  
![image](https://user-images.githubusercontent.com/62248851/216961325-24290b6c-09a9-462d-a16f-a72d08907bd7.png)

this happened on funkwhale, and wordpress as well

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/grid_weblets/issues/1115
https://github.com/threefoldtech/grid_weblets/issues/1253

**Comment by A-Harby** [comment]
Issue solved in most of deployments but still happens in the wordpress.
![image](https://user-images.githubusercontent.com/109473873/221421839-5bd47bf3-908b-4a16-9d3b-e05a864eabe2.png)

**Comment by mohamedamer453** [comment]
The issue is still present on devenet weblets `43f6954` in multiple weblets.

### Peertube

[Untitled_ Mar 20, 2023 1_19 PM.webm](https://user-images.githubusercontent.com/101194226/226329999-c4ab8389-7405-41f3-8161-b05652198fa4.webm)

### Funkwhale

[Untitled_ Mar 20, 2023 1_23 PM.webm](https://user-images.githubusercontent.com/101194226/226330052-dd549f01-ceb1-488e-8127-e66ff3c9148a.webm)

### Mattermost

[Untitled_ Mar 20, 2023 1_28 PM.webm](https://user-images.githubusercontent.com/101194226/226330089-a20a3f2d-5f5f-40f1-bb27-9514d6a0a016.webm)

### Discourse

[Untitled_ Mar 20, 2023 1_31 PM.webm](https://user-images.githubusercontent.com/101194226/226330141-cf5ff639-f44e-4103-9fa0-43be7c73314c.webm)

### Taiga

[Untitled_ Mar 20, 2023 1_37 PM.webm](https://user-images.githubusercontent.com/101194226/226330170-2e4118ee-ccc3-487e-ad8b-5ced742d34d8.webm)

### OwnCloud

[Untitled_ Mar 20, 2023 1_41 PM.webm](https://user-images.githubusercontent.com/101194226/226330195-5df87831-cf44-4a9e-8e60-c99dba633d45.webm)


I wasn't able to verify if it's fixed or not in `CapRover`, `Casperlabs`, `Node Pilot` since there are no public ips available on devnet.

**Comment by mohamedamer453** [comment]
and sometimes the error appears in the `Micro VM`

![image](https://user-images.githubusercontent.com/101194226/226337487-3ab236cb-7203-4fc1-b10d-ef2b6f947422.png)

**Comment by A-Harby** [comment]
Verified on devnet, 
Deployed [Peertube - Funkwhale - Mattermost - Discource - Taiga - Owncloud - Umbrel - MicroVM] and Back button was working fine in all of them.
