### ISSUE TITLE
the error message in the profile manager does not disappear after closing and opening it

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1291]
### Search first

Search for similar issues first, if not complete the following template

### Description

the error message in the profile manager does not disappear after closing and opening it again even after removing the Mnemonics 
[Screencast from 02-08-2023 11:26:27 AM.webm](https://user-images.githubusercontent.com/110984055/217489881-33463da8-392f-4538-8bd9-dfd12793340e.webm)

### Steps to reproduce

1. go to the playground
2. go to the profile manager
3. insert an invalid Mnemonics
4. the error message will appear
5. remove the Mnemonics
6. the error message doesn't disappear
7. try to close and open the error message is still there

![image](https://user-images.githubusercontent.com/110984055/217490411-bce66afe-1582-48d8-b450-667d6b59f5c5.png)

**Comment by zaelgohary** [comment]
Profile manager errors are persistent because of cases like the one shown below. Validation errors should not disappear even if the modal is closed because the data won't be erased from the field, hence, the validation would still be working.

![image](https://user-images.githubusercontent.com/40770501/218745429-aff0505f-0da8-4efd-bf72-db05d38e5ed7.png)
