### ISSUE TITLE
Profile migration failed - testnet

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1297]
I loaded a new version of the testnet playground and found my profile was missing. There's a migrate button, but it's not active. Why not? Can't we migrate using the existing profile and password online?

I supplied the seed phrase for one of my accounts, then hit the migrate button, and migration failed:

![image](https://user-images.githubusercontent.com/17682591/217891557-a7f650e2-b495-426d-95f9-c0bbef6b0a3f.png)

Console logs:

![image](https://user-images.githubusercontent.com/17682591/217890441-d436a08f-0c6c-4554-8902-6e7a6c400d28.png)

For the user experience, this becomes a dead end. The only path forward is to click the `Migrate` button in the upper right corner of the box. That button returns to the new profile creation flow, so perhaps its label should change to `New` or `Create`. There should also be a way forward for the user at this point, either to proceed with the keys that were successfully migrated or to create a new profile with the provided seed phrase.

**Comment by zaelgohary** [comment]
The profile manager now works as follows:

- You paste your mnemonics and if there were an existing account for the mn, your profile info would be displayed without the need to press any buttons as shown below

![image](https://user-images.githubusercontent.com/40770501/218767925-24a7d98e-a3bd-4694-a1ad-174556c39cd8.png)

- If this is a new account, the create account button will be enabled as shown below

![image](https://user-images.githubusercontent.com/40770501/218768345-c9ec4981-4516-485d-9096-a763eb61be02.png)

The only case where you need to press the migrate button is when you had a profile with keys stored in it with the password as a secret instead of mnemonics. 

I edited the message for the failed migrated keys as it was a bit ambiguous as you said but in your case, the failed migrated keys were due to disconnection.

**Comment by coesensbert** [comment]
Had the same on mainnet v1.6.0

![image](https://user-images.githubusercontent.com/88312671/220319171-2d69c31d-61eb-4d8e-9574-99c292e03f48.png)

**Comment by khaledyoussef24** [comment]
verified on testnet different accounts
![image](https://user-images.githubusercontent.com/110984055/225599444-e3531da3-4ec5-49f5-a1c1-6e0e2b71b46d.png)
![Screenshot from 2023-03-16 13-07-51](https://user-images.githubusercontent.com/110984055/225598970-de46e62e-e9e0-408c-aad6-6e0abf6fa134.png)
![Screenshot from 2023-03-16 13-07-39](https://user-images.githubusercontent.com/110984055/225598982-6260cfb8-995f-4f71-b92a-bf6851829c8c.png)
