### ISSUE TITLE
[Bug 🐞]:  My Testnet playground Profile has some problems 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/grid_weblets#1301]
### What happened?

After nearly a year of test and breaking deployments I have accumulated some "nuisance" issues with my Test Net Deployment profile. I'm Putting this here because i'm unsure where the issue actually originates.

For the first issue I have is this 

![image](https://user-images.githubusercontent.com/44621168/217319676-63e0be0a-b7f8-4ae5-98fb-2b937b8ef9aa.png)

This issue started when I broke a deployments network interfaces making it permanently unable to be accessed, again this is just a nuisance, it doesn't seem to have any affect. 

then today when I setup with the new profile manager i got this 

![image](https://user-images.githubusercontent.com/44621168/217320753-c053c7bb-8a2f-4149-ab9c-1fe5adcce1f2.png)

I'm not having any signs of anything not working properly but I'm worried I need to figure out what I've broken and how to fix it before I start having issues 

### What did you expect?

A way to delete the failed workload and an explanation of what 8 keys failed to import. This account had 1 deployment active at migration.

**Comment by zaelgohary** [comment]
![image](https://user-images.githubusercontent.com/40770501/218791651-02d96d1b-11f2-42ee-8f08-40252b889e97.png)

The above warning could happen due to multiple reasons:
- Some keys failed to migrate which led to failure when loading deployments
  - The reason for this may be the failed keys are encrypted with a different password (the wrong password was entered) or not encrypted or a disconnection happened while migrating. Already edited the failed message in [#1306](https://github.com/threefoldtech/grid_weblets/pull/1306)

- The node which has the deployment is down
  - In this case, the warning should disappear once the node is up again

**Comment by Parkers145** [comment]
So as long as I have access to all my workload, I should be in good shape?

**Comment by xmonader** [comment]
> So as long as I have access to all my workload, I should be in good shape?

Yes.

**Comment by khaledyoussef24** [comment]
tried different methods migration succeeded 
![Screenshot from 2023-03-16 13-09-43](https://user-images.githubusercontent.com/110984055/225605251-87fcab92-e70f-498d-a4de-bffdde7027af.png)
![Screenshot from 2023-03-16 13-07-39](https://user-images.githubusercontent.com/110984055/225605307-ac1f8aba-d6f0-4ae8-838d-90064101d1ab.png)
