### ISSUE TITLE
Capacity Filter: Node ID is displayed as `null` when you enter resources that doesn't match any of the available nodes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1358]
### Description

The capacity filter displays null instead of the node idea when a valid value is entered but no node is available with the mentioned resources.

[TF Playground (5).webm](https://user-images.githubusercontent.com/101194226/224048811-3d4017d9-c46e-4510-8f00-45b0fca7efc0.webm)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Select any weblet.
- Select the capacity filter.
- Wait for the capacity filter to load.
- Select `Custom` from the `Solution Flavor` list.
- In the memory or disk fields enter the maximum number allowed for the field.
- Wait for the capacity filter to load again.

**Comment by A-Harby** [comment]
Devnet, b4b84b3
Still reproducible, tried with peertube
node (Null) and deploy button was enabled.
![image](https://user-images.githubusercontent.com/109473873/230393370-3137303b-559a-4955-9c63-7e3561fcd0cb.png)

**Comment by 0oM4R** [comment]
I think this happens only if you change some values while validating, @A-Harby @mohamedamer453 can you confirm that ?

**Comment by A-Harby** [comment]
After some investing with @0oM4R, the issue was changing the values while the capacity filter is validating the node with old resource.

### steps to reproduce:
1. Choose any solution.
2. Select Capacity filter from node selection.
3. Press Apply filter button.
4. While the node is being validate, Change any resource.

As you can see, in second time applying filter I changed the value of the memory while validating is still working which cause the null issue to appear. 
[Untitled_ Apr 9 2023 12_44 PM.webm](https://user-images.githubusercontent.com/109473873/230768140-8cf03dfc-6cf9-4493-80b0-5cee15de9867.webm)

**Comment by A-Harby** [comment]
Verified on Devnet,
Null node isn't shown again.
![image](https://user-images.githubusercontent.com/109473873/230871920-95cf48a7-99fc-4d32-ba14-21e8b3fa2609.png)
