### ISSUE TITLE
Can't add a worker after deploying a Kubernetes master.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1410]
### Description

Testnet, v1.7.0-rc1

Can't add a worker after deploying a Kubernetes master.

1. Deploy a Kubernetes master.
2. Click on manage workers from Kubernetes master deployment.
3. deploy worker   

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/227966694-64184e87-b835-42fc-aee8-295373a66964.png)

**Comment by A-Harby** [comment]
Same happens when trying to delete a worker after deploying both master and worker.

![image](https://user-images.githubusercontent.com/109473873/227970070-5c58365d-4044-4f1c-a367-d58a9efc0e85.png)

**Comment by 0oM4R** [comment]
please test caprover also

**Comment by mohamedamer453** [comment]
Verified on devnet.

Adding a kubernetes worker is back to normal and the worker was added without any issues.

![image](https://user-images.githubusercontent.com/101194226/228479283-f505f3a9-ac8c-48fc-8b66-aa49e71cf628.png)

![image](https://user-images.githubusercontent.com/101194226/228479600-2c9ecf11-e0c5-430d-9645-eb835a93ef5e.png)

Also deleting workers is working without any issues.

![image](https://user-images.githubusercontent.com/101194226/228480482-79bee718-b7ad-4784-807b-9894113d67bb.png)

![image](https://user-images.githubusercontent.com/101194226/228480598-03ed98ac-5a5b-44ee-960c-e1160e506bb5.png)



> please test caprover also

Unfortunately i wasn't able to test CapRover due to the in-availability of public ips on devnet.

![image](https://user-images.githubusercontent.com/101194226/228481834-15200776-ae3e-4bb5-9867-bd8d23cc5a5e.png)
