### ISSUE TITLE
cannot ssh into VM deployed with the alpine flist 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#161]
cannot SSH to a VM machine that is deployed using the weblet in https://play.grid.tf, as it asks for the root user's password.

This affects the Alpine image, using both the public and Yggdrasil IPs.

The Ubuntu image works fine.

see: https://circles.threefold.me/project/test-tfgrid3/issue/37

**Comment by xmonader** [comment]
quoting @OmarElawady 
> If the used key is of type ed25519, it's not supported by this flist since it uses dropbear not openssh.
There was an issue a while ago that might have caused this problem. The decommissioned VMs weren't destroyed immediately. So in case someone reused a public ip that was attached to a VM that is decommissioned but not destroyed yet, a conflict happens and they race for this public IP causing external requests to skip a random one and go to the other. It should be fixed in https://github.com/threefoldtech/zos/issues/1486
If possible, try SSHing through the wireguard ip and yygdrasil ip to pinpoint the exact issue.


https://circles.threefold.me/project/test-tfgrid3/issue/20

**Comment by sameh-farouk** [comment]
in the alpine image, Root user is locked by default
the password in `/etc/passwd` file looks like:

```
# head -n 1 /etc/shadow
root:!::0:::::
```

by using `*` instead of `!`? - It allows using ssh with private keys authentication while disabling using password

this one works well, 
https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-alpine-3.flist
