### ISSUE TITLE
Grid weblets build time needs improvement

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#27]
Build time takes approximately 54 seconds.

**Comment by Omarabdul3ziz** [comment]
### Update
after adding many weblets since this issue was created. the build time now takes about 2 minutes. and it is really time-consuming while developing cause with each small change you need to rebuild the project again.

### Suggestions
Maybe we should use multi-threading options like `worker-threads` to speed up the bundling time.

**Comment by abom** [comment]
AFAIK, the build just builds all `weblets`. I don't know if we can parameterize the build script to only build/copy certain `weblet` (the one which has actual changes).

**Comment by mohamedamer453** [comment]
Verified.

you can build only the changed weblets by specifying them though the `TARGET_WEBLETS` env var and this leads to a much faster build time since it only builds the selected module/s.

You start by exporting `TARGET WEBLETS` with a single module or multiple ones separated by a space 

```
export TARGET_WEBLETS="vm"

or 

export TARGET_WEBLETS="vm kubernetes peertube"
```

and after exporting `TARGET_WEBLETS` you can execute `yarn serve:app` and it will only build the selected module/s
