### ISSUE TITLE
why there is an extra 25GB added to the SRU value given by the user for both peertube and vm deployments?

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#326]
### Description

in peertube and VM weblets the filter will add an extra 25GB to the SRU value given by the user. in Kubernetes and CapRover weblet it looks for the given value without changes. is that intended?

**Comment by Omarabdul3ziz** [comment]
this happens because the filter search for the total storage of ( default value of rootfs + the provided value for storage )

https://github.com/threefoldtech/grid_weblets/blob/f8930e488488e45d2a51da9c607f0064e174f1fb/src/elements/peertube/Peertube.wc.svelte#L144-L147

https://github.com/threefoldtech/grid_weblets/blob/f8930e488488e45d2a51da9c607f0064e174f1fb/src/types/vm.ts#L44

**Comment by sameh-farouk** [comment]
do we need to add this to the SRU value in Kubernetes node and CapRover VM deployments?

**Comment by Omarabdul3ziz** [comment]
this is not the case right now. I think it fixed in this commit `cdb74a08`, removing the default value of the rootFS which was 25GB. now the filter search for a node that has storage follows this formula
https://github.com/threefoldtech/grid_weblets/blob/0a7f7a029a15ce077576d2dc4ca159193da91908/src/elements/peertube/Peertube.wc.svelte#L156-L159
adding to the selected disk size a rootfs which computed as 
https://github.com/threefoldtech/grid_weblets/blob/0a7f7a029a15ce077576d2dc4ca159193da91908/src/utils/rootFs.ts#L5-L18

now when choosing `diskSize=1000` the filter adds only 2GB "based on the CPU and RAM" and searching for node has `sru=1002`
![Screenshot from 2022-02-01 17-58-03](https://user-images.githubusercontent.com/32527347/152003671-cfdda5f0-ac66-4165-acba-1c6ba9824750.png)
