### ISSUE TITLE
Hidden node (30) shown in capacity filter

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#395]
![image](https://user-images.githubusercontent.com/31689104/147746126-99a08209-cf3a-4feb-aa36-ac5e0126d67c.png)

**Comment by RafyAmgadBenjamin** [comment]
I can't reproduce this scenario

**Comment by RafyAmgadBenjamin** [comment]
i have opened an issue in TS client as it is the one responsible for the capacity filter and the one who returned the hidden the nodes

Open issue in TS client
https://github.com/threefoldtech/grid3_client_ts/issues/193

**Comment by RafyAmgadBenjamin** [comment]
After discussing the issue with @waleedhammam, that we need to add `addAccess=true` while we deploying  to be able to deploy on a hidden node 

under this line
https://github.com/threefoldtech/grid3_client_ts/blob/36cd4c99dcc53516f2ee829a9fd54ff7030a8363/scripts/single_vm.ts#L8

**Comment by MohamedElmdary** [comment]
![image](https://user-images.githubusercontent.com/31689104/148030645-07b08536-190a-4b52-8942-4d914dcc09f1.png)

**Comment by OmarElawady** [comment]
This node is hidden means it doesn't have a public ipv6 or a public ipv4, so it can't be used in a network with other nodes if none of them have a public ip4. So a network with:
- 1 hidden node: good
- 1 hidden node and 5 nodes all with public ipv6 but none with public ipv4: bad
- 1 hidden node and 1 node with ipv4 and five other nodes (doesn't matter what they are): good
![image](https://user-images.githubusercontent.com/13040543/148033604-c13585c7-ce05-4c95-b383-0dc51ac6bd40.png)

The last error is just the node not having enough memory. As Rafy indicated, it's an issue with the capacity filter for returning a hidden node on a network with no public ipv4 nodes. It can be fixed by returning first non-hidden nodes if any (will probably never pick hidden nodes in this case), or making the capacity filter has the knowledge of whether hidden nodes are allowed based on the used network.

**Comment by MohamedElmdary** [comment]
Should be tracked in https://github.com/threefoldtech/grid3_client_ts
