### ISSUE TITLE
Taiga (circles) weblet

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#409]
Make sure to have the minimum requirements in #406.

**Comment by RafyAmgadBenjamin** [comment]
I have reached our discourse forked repo and found that we maintain an image which deploy the whole thing, I have tested it and it is working but it takes while due to the lack of docs and description for the environment variables used in this image but it is working and I have tested the tf connect and it is working also

**Comment by sameh-farouk** [comment]
status update:
this was almost implemented in these PRs
weblet:
https://github.com/threefoldtech/grid_weblets/pull/452
image:
https://github.com/threefoldtech/tf-images/pull/61

per the discussion, the VM starting time was longer than the expectations and @rkhamis asked to try another approach to implement the flist image (install from the source code instead of docker setup).
@rkhamis suggests also that @Omarabdul3ziz can pick this issue and work on the alternative image.

**Comment by sameh-farouk** [comment]
I have also opened an issue related to the Docker bad performance on grid3 VM.
https://github.com/threefoldtech/cloud-container/issues/11

**Comment by sameh-farouk** [comment]
**status update:**
the problem with the starting time of Taiga VM wasn't related to the approach used to installing taiga, but to the fs type of the directory where docker store the images and create the containers. mounting a disk on /var/lib/docker which was going to add anyway solved the issue as the disk has btrfs type.

waiting for reviewing the PRs and to be approved.

**Comment by sameh-farouk** [comment]
**status update:**
PR Merged to the development branch, and the issue moved to the Verification.

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/150100642-e88789dd-4e8c-4a1f-8f86-dd5c6d039533.png)
