### ISSUE TITLE
Deployment list is inconsistent with it's returned result

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#535]
Sometimes it returns my full list of VM deployments and sometimes only a subset is returned 

![image](https://user-images.githubusercontent.com/9322121/152684936-e1b96982-b199-431e-816c-97cb422fe67b.png)

![image](https://user-images.githubusercontent.com/9322121/152689019-15687559-2bb6-45c2-a975-f6778bfebf01.png)

**Comment by dmahmouali** [comment]
what happened is we are getting the deployment over RMB by running the `zos.deployment.get` command and when the command fails, the weblet can't list the VM but it's still reachable over planetary network IP or public IP.

maybe the command failed because the node became down or unreachable over planetary IP.

**Comment by abom** [comment]
I think we should re-verify this?

**Comment by MohamedElmdary** [comment]
I think this issue related to what @dmahmouali said because I'm ignoring the deployment info whenever it throws an error

**Comment by abom** [comment]
For verification

**Comment by Omarabdul3ziz** [comment]
verified
![Screenshot from 2022-03-20 10-53-38](https://user-images.githubusercontent.com/32527347/159155996-0e5da206-8933-42be-8df5-bae65a42baec.png)
