### ISSUE TITLE
TC443: Verify Mattermost 

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#635]
Such URL as described in the test case is not available

![image](https://user-images.githubusercontent.com/65153287/162134178-2303c22f-068c-40f1-80c0-a15b14e16fba.png)

**Comment by mohamedamer453** [comment]
The issue is related to an outdated test case with an expired deployment link.
I updated the test case and you can find it [here](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3436340).

And testing for Mattermost should be done by deploying a new instance like all the other deployments.
