### ISSUE TITLE
Improve presearch capacity filter

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#665]
Presearch doesn't require a public IP for deployment, but more than one instance won't be registered if they are deployed on the same node behind NAT.

### Improvement
- Optional public IP can be provided which should work if it's selected.
- In case NO public IP was selected, the contract's data of the Presearch deployment should contain a word like `Presearch` which indicates that this node already has a deployment that uses the node IP for registration, so the capacity filter can start to exclude these nodes.

**Comment by Omarabdul3ziz** [comment]
verified on dev playground.

- in case not choosing a public IP. it should only allow one deployment per farm
  here only nodes that are not in `freefarm`
  ![image](https://user-images.githubusercontent.com/32527347/183396324-4e332990-cb91-42d0-8cba-0e6995c224d2.png)

  since `freefarm` already has a presearch deployment without public IP
  ![image](https://user-images.githubusercontent.com/32527347/183396513-fcbf6b61-3ba8-4208-a08e-e6dceb1f42c7.png)

- in the case of choosing a public IP, it should list all the nodes that belongs to farms that has a public IP
  ![image](https://user-images.githubusercontent.com/32527347/183397640-c962adcb-56fe-43c2-8e18-7f41b5c9d3e6.png)

  checked all the free public IPs either farms is offline or dedicated

works as expected.

**Comment by Omarabdul3ziz** [comment]
After further testing. deploying on node 41 without public IP. the same node is still in the capacity filter after that.

the reason is the word `presearch` in metadata changed to be in upper case so it is not matched with the `exclusiveFor` value
https://github.com/threefoldtech/grid_weblets/blob/dd1eaa6f79436c30c8be7ac1891637c2963b21ea/src/utils/deployPresearch.ts#L82
https://github.com/threefoldtech/grid_weblets/blob/dd1eaa6f79436c30c8be7ac1891637c2963b21ea/src/elements/presearch/Presearch.wc.svelte#L167

**Comment by khaledyoussef24** [comment]
can't deploy presearch on devnet
![Screenshot from 2022-08-22 09-25-33](https://user-images.githubusercontent.com/110984055/185869399-be87dc4c-12a8-43b2-b213-b09b5a14a782.png)
![Screenshot from 2022-08-22 09-48-51](https://user-images.githubusercontent.com/110984055/185869407-95f6311c-4756-42c8-a056-790b51f6c46d.png)

**Comment by Omarabdul3ziz** [comment]
> can't deploy presearch on devnet ![Screenshot from 2022-08-22 09-25-33](https://user-images.githubusercontent.com/110984055/185869399-be87dc4c-12a8-43b2-b213-b09b5a14a782.png) ![Screenshot from 2022-08-22 09-48-51](https://user-images.githubusercontent.com/110984055/185869407-95f6311c-4756-42c8-a056-790b51f6c46d.png)

this error is not related to the weblets it is a node issue. I faced a similar problem on node 186 on test net and opened an issue on zos repo. can you please comment there.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Currently when i checked only the `Planetary IP` filter i got zero nodes found in the capacity filter.


![image](https://user-images.githubusercontent.com/101194226/187184153-77fbdf46-8532-445e-8310-4c9a52b88970.png)

and when i checked the contracts with `presearch` metadata from graphql i got these contracts.

![image](https://user-images.githubusercontent.com/101194226/187184367-16fb3375-0796-44f1-b480-65047d5ae3e7.png)

the first one of them didn't have a public ip so it was the only one that could be deployed on `FreeFarm` . and the other nodes on devnet that didn't belong to `FreeFarm` were either out of resources or rented.
