### ISSUE TITLE
Sudden disconnection of a PRE node on testnet, and also playground gives sudden error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#669]
Issue with deployment using IP address 185.206.122.135 , contractID 3844, nodeID 15 : suddenly disconnected on May 4. 

<img width="1280" alt="Screenshot 2022-05-04 at 17 59 22" src="https://user-images.githubusercontent.com/30384423/166722835-17264f7f-58c1-487b-be63-3e2799953028.png">

**Comment by Omarabdul3ziz** [comment]
deployed an instance with contract id 5865 on node 41 on dev net to see if it will happen again

**Comment by Omarabdul3ziz** [comment]
checked the deployment mentioned above and couldn't find it.
I got the following error 
![image](https://user-images.githubusercontent.com/32527347/187250005-30dadb5f-c1db-47f6-8af5-f61b1754e328.png)

it can't connect to the node it was deployed on which was node 41
![image](https://user-images.githubusercontent.com/32527347/187250832-3045ebc9-6b4c-4ec7-ad73-a76656ae3f9b.png)

checking node 41 state https://gridproxy.dev.grid.tf/nodes/41 looks like it gets up less then one day ago with a different twin id.

so it may be the contract was deleted because the node get down.

I made another deployment on a different node to check if it will happen again 6886 on node 27

**Comment by Omarabdul3ziz** [comment]
@mohamedamer453 kept these 5 instances from [this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/130) running for about a month and they did not disconnect. 

Most likely the instance on the original issue disconnected for a node operation problem ( reboot, or downtime ) as what happens for the instance from my previous comment.

**Comment by Omarabdul3ziz** [comment]
If it happens again please reopen this issue.
