### ISSUE TITLE
No.28 - Test case: TC667 (Capacity packages are all the same)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#736]
Version v1.4.1-rc2
Deployed on Testnet

Select Capacity Package ( min , standard , recommended ) are created with same CPU , Memory , Disk data. For example deployed Owncloud 
![image](https://user-images.githubusercontent.com/65153287/169267350-db3ed186-c7dd-4a79-b4cb-8988496ca579.png)

![image](https://user-images.githubusercontent.com/65153287/169267388-17ae1c0a-c748-4472-9f1f-25fd06f72f8a.png)

![image](https://user-images.githubusercontent.com/65153287/169267422-0b6454d5-e70d-48c1-b55a-f3234470096a.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

As mentioned in #740 the issue was related to `Discourse` & `ownCloud` and it's fixed now and the packages reflect the correct values for (CPU, Memory, Disk)

### Owncloud

- Minimum (CPU: 2, Memory: 16384, Disk: 250)

    ![image](https://user-images.githubusercontent.com/101194226/170461717-c95f11d2-e025-4dc9-9f23-271e3ce5f8f5.png)

- Standard (CPU: 2, Memory: 16384, Disk: 500)

    Currently there are no nodes on devnet with enough `sru` so i wasn't able to depoly either the `Standard` or `Recommended` packages but you can check that the packages actually apply by selecting the desired package then selecting  `Custom` and the fields will be filled with the specs of the most recently chosen package.

    ![image](https://user-images.githubusercontent.com/101194226/170468458-4f8d0b5e-57b0-4a63-b877-74d946965315.png)


- Recommended (CPU: 4, Memory: 16384, Disk: 1000)

    ![image](https://user-images.githubusercontent.com/101194226/170468647-7b8b6451-e47d-4eb5-acdc-b405f66c5001.png)


### Discourse

- Minimum (CPU: 1, Memory: 2048, Disk: 10)

     ![image](https://user-images.githubusercontent.com/101194226/170469507-1e3e2f29-7819-4253-950f-3fc606f79c59.png)

- Standard (CPU: 2, Memory: 2048, Disk: 50)

    ![image](https://user-images.githubusercontent.com/101194226/170470007-62b36dd7-6548-494c-b161-343c1b38d766.png)

- Recommended (CPU: 4, Memory: 4096, Disk: 100)

    ![image](https://user-images.githubusercontent.com/101194226/170470892-b4ae2a99-d909-4603-9302-0fb9c76ac3e9.png)
