### ISSUE TITLE
Feature request: set full vm's as default for 'Virtual Machine'

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#759]
### Description

Currently a virtual machine is based on these flists: https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist ..
Which are not real vm's.

### Implementation

Use the flists provided here as a default for VM deployments: https://hub.grid.tf/tf-official-vms
These are full vm flists which solve a lot of previous issues with deployments. They will give users a much better experience.

### More

Requirements to deploy a full vm:

- Extra disk -> which will become the VM root disk

Docs: https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/zmachine.md

**Comment by DylanVerstraete** [comment]
Can we use this feature for all other predefined services as well (k8s, owncloud, ...)

**Comment by xmonader** [comment]
Implementation notes: 
- create the disk in the background to be mounted on /

**Comment by mohamedamer453** [comment]
Verified on devnet.

A new `Full VM` solution was added that uses flists from https://hub.grid.tf/tf-official-vms and has a disk option `50 GB` by default that is used as a mounting point instead of `Root FS`

![image](https://user-images.githubusercontent.com/101194226/183291079-ea3c8eac-80c1-427d-a1f5-a15b431a2fd8.png)


and i was able to successfully deploy 3 vms with the 3 default flist options (Ubuntu 18.04, 20.04, 22.04)

![image](https://user-images.githubusercontent.com/101194226/183291478-b993cb8d-a410-4448-9575-f16d1c2bad1f.png)

![image](https://user-images.githubusercontent.com/101194226/183291463-33c45628-91cb-463c-97a4-f89d59866fac.png)

### 18.04

![image](https://user-images.githubusercontent.com/101194226/183291055-10b21013-169c-4dfb-8f29-42f8eac70915.png)

### 20.04

![image](https://user-images.githubusercontent.com/101194226/183291328-5ec5ab48-9476-4ada-92d4-3df47beb13cb.png)

### 22.04

![image](https://user-images.githubusercontent.com/101194226/183291776-231df8ad-9fc3-4096-9747-f70bb078c864.png)
