### ISSUE TITLE
Lost connection to wallet on devnet, but workload still running

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#767]
I launched a workload on April 12 on devnet, I see it's still running (PRE node which still gives connection). 

Contract ID 164, IP address 185.206.122.33

<img width="1246" alt="Screenshot 2022-06-01 at 09 49 01" src="https://user-images.githubusercontent.com/30384423/171356205-07abcd20-a469-4ecd-b2d4-d52ace6de5cb.png">

No idea whether there is still a balance open and if I still pay. Anyway, the workload still runs. 

When I try to SSH into the, I can't connect either (even though I know it's still running) because it says that rsa key is wrong (which can't be correct, I use the same rsa key for all my deployments). 

<img width="694" alt="Screenshot 2022-06-01 at 11 33 54" src="https://user-images.githubusercontent.com/30384423/171378172-fcd2a272-5505-4a26-ad0d-63b194a75558.png">

**Comment by AhmedHanafy725** [comment]
this error doesn't mean that the ssh key was changed, but the machine identification is what was changed here, this may happen if the machine is redeployed for any reason. removing the host key of the machine from the `~/.ssh/known_hosts` should solve the problem

**Comment by gmachtel** [comment]
No we promise with the playground to have a pure click’n’go solution. Are AWS or DO users also referred to ssh docs ? Plus: redeployment of a machine is an event happening on the grid, no ?

**Comment by xmonader** [comment]
> No idea whether there is still a balance open and if I still pay. Anyway, the workload still runs.

If the user loses their wallet or mnemonics, there's nothing we can do about it. the workload will keep running until the wallet is out of funds and done with the grace period.


For the SSH issue, no that most likely won't happen on AWS or DO (because they have tons of IPs) unless you used the same IP (which is a feature they offer), in this case we just recycling through limited amount of IPs so you have higher chances of facing that. Let's add that to our documentation as a possible scenario the user might face.

**Comment by gmachtel** [comment]
Thing is that I did not change anything to the workload, IP should only be reused after expiry of the old deployment.

And about mnemonics: opposite is happening from what you describe:
- I still know the mnemonics
- It looks like blockchain has lost twin ID, I had to re-sign and then it created another twinid linked to the wallet
- Workload still running but I’m sure there is no more tokens available on the wallet
