### ISSUE TITLE
Discourse Verify input/configuration validation not work correctly

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#795]
1. Create Discourse with MIN data (select custom package)
![image](https://user-images.githubusercontent.com/106578096/171564842-96178e3b-23b4-4edd-9c44-671d54a772f1.png)
Error mess:
![image](https://user-images.githubusercontent.com/106578096/171564871-406688e6-626a-4b19-9228-dd49225e1f46.png)
2. Mail server is empty and hasn't error message
![screenshoteasy - 2022-06-02T091419 231](https://user-images.githubusercontent.com/106578096/171564963-fb4e0bcd-f3cf-4db5-a8eb-da11cfced342.png)
Version v1.4.2
Deployed on Testnet
No.38 - Test case: TC722

**Comment by mohamedamer453** [comment]
Verified on devnet.

### Min configuration

The error regarding the minimum configuration was fixed and now the min memory is changed to `256` instead of `250` which was causing the mentioned error.

The min allowed now is `256`

![image](https://user-images.githubusercontent.com/101194226/173222827-ffff76ce-1545-4542-a88e-b413428d4437.png)

and i was able to successfully deploy an instance with the mentioned min configuration.

![image](https://user-images.githubusercontent.com/101194226/173223020-00295910-b290-4a19-af40-0a785da74504.png)

### Mail Server Configuration

Mail server configuration now has working validation and error messages. And the errors disable the deploy button

![image](https://user-images.githubusercontent.com/101194226/173222725-189be26b-eaea-4706-8755-1bc5b56ce661.png)
