### ISSUE TITLE
Add Node Pilot deployment

### ISSUE THREAD

**Issue by maxux** [threefoldtech/grid_weblets#825]
### Description

A new tab will be needed to deploy a `Node Pilot` instance. With few click, end user should have a working instance.

### Implementation

It's basically a VM with customs settings:
- VM Image: `https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist`
- Entry Point: `/` (not needed)
- CPU: `8`
- Memory: `8192`
- Public IPv4 required
- Public IPv6 required
- Planetary not needed
- Disk: first disk of `15 GB`
- Disk: second disk of `500 GB`

We will discuss on how to execute a script on that VM to setup the machine.

**Comment by AhmedHanafy725** [comment]
> * Disk: first disk of `15 GB`
> * Disk: second disk of `500 GB`

@maxux where these disks should be mounted?

**Comment by maxux** [comment]
It's a cloud-init VM, this doesn't matter, the mountpoint is ignored :)

**Comment by rawdaGastan** [comment]
I deployed the machine but I couldn't ssh to it. Is that normal?
Also I have passed the ssh_key as env or it should be something else?
@maxux

**Comment by maxux** [comment]
It works the same way as `Virtual Machine`, it's unmodified image right now. Environment `SSH_KEY` should be enough.

**Comment by rawdaGastan** [comment]
@maxux when I tried to ssh it gave me this: `Permission denied (publickey).`

**Comment by maxux** [comment]
Please use image: `https://hub.grid.tf/maxux42.3bot/maxux-nodep.flist`
Image works out-of-box on my tests (node pilot is reachable over https and zdbfs is running).

**Comment by maxux** [comment]
Quick summary can be found on the readme: https://github.com/threefoldtech/node-pilot-light/#basic

**Comment by rawdaGastan** [comment]
@maxux we used 100 GB disk instead of 500 GB one as we don't find capacity to deploy it on `devnet`.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Node Pilot Deployment was added to the weblets and i was able to successfully deploy an instance of it.

![image](https://user-images.githubusercontent.com/101194226/174781470-c7d3d8e4-8d86-4842-a6e2-8503bfbce1de.png)


![image](https://user-images.githubusercontent.com/101194226/174781597-40b34d95-d5bf-4de1-a399-53b5c84d9da7.png)



there should be a button in the deployment list like all the other deployments to redirect the user to `https://publicip`  because there's currently no way for the user to access the instance and it's not mentioned anywhere in the weblets that the user should navigate to `https://publicip` to access the instance.

![image](https://user-images.githubusercontent.com/101194226/174782351-46c7901b-99c3-4a57-8f7b-74db132f5c0e.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

A button was added to redirect the users to their instances instead of manually navigating to `https://publicip`.

![image](https://user-images.githubusercontent.com/101194226/175804691-43f8f287-2f2c-45ff-92e8-cef9b971e726.png)


![image](https://user-images.githubusercontent.com/101194226/175804725-c2838310-aa59-4a81-aced-9db195fde014.png)
