### ISSUE TITLE
UI adjustment - default Profile Name

### ISSUE THREAD

**Issue by renauter** [threefoldtech/grid_weblets#842]
When user go to dashboard and creates profile the default profile name ("Profile 1" / "Profile 2" / ...) generates an initial warning message
Indeed text field validation only accepts alphanumeric characters and default names have spaces on it 
Could be avoided be defining new default names like "Profile1" (no warning msg) or empty default name (warning msg but for obvious reason)
Please check if there are other similar cases for consistency

![Screenshot from 2022-06-22 11-12-41](https://user-images.githubusercontent.com/73958772/175051086-aa7a3b7a-0dd3-4866-9b95-c13e37b3c0a6.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The newly added profiles are now generated without a whitespace so they will not produce a validation error by default since whitespaces are not allowed in the Profile Name field.

![image](https://user-images.githubusercontent.com/101194226/176419155-2fd170ce-1e3c-4291-831a-b597dd9a9e7a.png)
