### ISSUE TITLE
Users shouldn't be able to change specs for Titan simulation 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/grid_weblets#988]
### Description

When selecting Titan on the simulator, it shouldn't be possible to change the specs since these are fixed.

**Comment by maayarosama** [comment]
From the following fields, What is considered as specs and should be disabled?
![specs](https://user-images.githubusercontent.com/66883096/197394693-698df9da-4e19-4343-a8cd-339bc5e38632.jpeg)

**Comment by xmonader** [comment]
@sabrinasadik can you please check

**Comment by sabrinasadik** [comment]
- GB
- Threads
- SSD
- NU
- Watt
- Certified node (should be on)

**Comment by mohamedamer453** [comment]
Verified locally since the simulator is only available on mainnet.

All of the mentioned fields are now disabled and the user can't change their default values. and the `Certified Node` option is selected by default.

![image](https://user-images.githubusercontent.com/101194226/201955012-78a0073f-c6ce-4180-9b1c-9d2883fc57fe.png)

Since this issue was verified locally i'll leave it open until it's released on mainnet and i can re-verify it there.
